### PR TITLE
Fix stream read error

### LINKED ISSUE #10: 03:17:06 [ERROR] client socket_err: 127.0.0.1:48304 failed to fill whole buffer
Hi there, I was trying out your crate today and noticed this error: `03:17:06 [ERROR] client socket_err: 127.0.0.1:48304 failed to fill whole buffer`.
  
I spent some time trying to fix it, and I am new to rust and ISO 8583, so maybe you can help me solve the problem and learn something along the way.

When I run `test_send_recv_iso_1100` the server emits this error, but it may be misleading.  `server.mli.parse` Throws an IsoError with `std::io::error::ErrorKind::UnexpectedEof` [here](https://github.com/rkbalgi/iso8583_rs/blob/0bc7ede98c002f2acc7dfc38394c1a45bd221b8b/src/iso8583/mli.rs#L40).

It may be because `in_buff` is being processed twice for some reason?  I can't quite tell.

### PR DESCRIPTION
**Pull request by chmoder**
This PR fixes https://github.com/rkbalgi/iso8583_rs/issues/10 by peeking at the stream to see if there are bytes available to read, if not then we know the stream is EOF and the client connection closed.

### CODE REVIEW

**Comment by rkbalgi** [comment]
This will work if the client reliably disconnects after sending a complete message. But, network failures could happen at any step, for example after reading the MLI here - `match reader.read_exact(&mut data[..]) {`
Or perhaps even after peeking? Now you're just peeking at one byte but a 4E/4I uses 4 bytes and a 2E/2I uses 2 bytes.

The code as-is assumes that the client is connected and makes a read attempt and fails if the client has disconnected and reports the same. What I think you're trying to do is to ensure that the client is connected (and that there is enough data to process a whole message) before proceeding?

**Comment by chmoder** [comment]
I see what you are saying about 4E/2E etc. and strangely enough I started with that approach.  However, at some point that seemed like a data validation thing that belonged in each respective `parse` method.

The fundamental reason `std::io::error::ErrorKind::UnexpectedEof` happened is simply that the client closed the connection and `parse` called `read_u16::<byteorder::BigEndian>()` on the stream with EOF `(OK(0))`.  This is because the TcpStream implementation sends EOF `(OK(0))` when the connection is closed.  

It a network failure occurs, `read` and `write` methods will return errors, and I think the existing implementation already handles them.

I am open to changing the design, but also want to summarize what I have learned to help us make good design choices.

**Comment by rkbalgi** [comment]
The `read_u16::<byteorder::BigEndian>()` will either return Ok(u16) or an Err(e) where e.ErrorKind==UnexpectedEof in case where the client closed the connection. 

(from byteorder-1.3.4\src\io.rs)

```    #[inline]
    fn read_u16<T: ByteOrder>(&mut self) -> Result<u16> {
        let mut buf = [0; 2];
        try!(self.read_exact(&mut buf));
        Ok(T::read_u16(&buf))
    }
```

So, Ok(0) is only possible if were trying to read a stream of bytes where next two bytes were 00 00

A better approach to detect would be to have method on the MLI trait like 'is_available()' which uses peek to return a bool (if there are 2 or 4 bytes available based on 2E/I or 4E/I) or an error (in case the client has disconnected)

**Comment by chmoder** [comment]
Thanks for the suggestion, I like the `is_available` solution better because it checks for the required amount of data;  Not just that some data exists.

File: src/iso8583/server.rs [hunk 1]
```diff
@@ -108,6 +108,11 @@ fn new_client(iso_server: &ISOServer, stream_: TcpStream) {
         'done:
         loop {
             if reading_mli {
+                match server.mli.is_available(&stream) {
+                    Ok(true) => true,
+                    IsoError => break 'done,
```
Comment (rkbalgi) [inline src/iso8583/server.rs]: shouldn't this be Err(e)=> break 'done,?

File: src/iso8583/mli.rs [hunk 2]
```diff
@@ -77,6 +90,15 @@ impl MLI for MLI4E {
         let _ = mli.write_u32::<byteorder::BigEndian>(n.clone() as u32);
         Ok(mli)
     }
+
+    fn is_available(&self, stream: &TcpStream) -> Result<bool, IsoError> {
+        let mut buf = vec![0; 4];
+
+        match stream.peek(&mut buf).unwrap() {
```
Comment (rkbalgi) [inline src/iso8583/mli.rs]: The unwrap could panic, so something like this should do?

```rust
match stream.peek(&mut buf) {
                    Ok(n) => {
                        if n==4{
                            Ok(true)
                        }else{
                            Err(IsoError { msg: format!("client disconnected")})
                        }
                    },
                    Err(e) => Err(IsoError { msg: format!("stream err. cause: {}",e.to_string())})
                }
```

Comment (chmoder) [reply src/iso8583/mli.rs]: Excellent solution!  Thanks for showing me that, I will be using this pattern often in the future.

File: src/iso8583/server.rs (hunk 1 above)
Comment (chmoder) [reply src/iso8583/server.rs]: Good catch, yes

**Review by rkbalgi — APPROVED** [review]
lgtm
